version: '3.8'

services:
  client-app:
    build: ./client-app
    ports:
      - "3000:3000"
  
  server-app:
    build: ./server-app
    ports:
      - "8000:8000"
    depends_on:
      - client-app